GXMH/urls.py
from django.contrib import admin
from django.urls import path, include
from GXMHAPP import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path('', views.index),
                  path('flush/', views.flush),
                  path('register/', views.register),
                  path('retrieve_password/', views.retrieve_password),
                  path('mailbox/', views.mailbox),
                  path('place/', views.place),
                  path('user_detail/', views.user_detail),
                  path('user_collection/', views.user_collection),
                  path('extract/', views.extract),
                  path('mh/', views.mh),
                  path('mh/mh_forum/', views.mh_forum),
                  path('mh/mh_detail/', views.mh_detail),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GXMHAPP/models.py
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.

class UserInfo(models.Model):
    portrait = models.ImageField(upload_to='portrait', default='portrait.jpg', verbose_name='头像')
    user_name = models.CharField(max_length=32, verbose_name='用户名')
    account = models.CharField(max_length=32, verbose_name='账号', unique=True)
    password = models.CharField(max_length=32, verbose_name='密码')
    region = models.CharField(max_length=32, verbose_name='地区')

    class Meta:
        verbose_name_plural = '用户信息'

    def __str__(self):
        return self.account
    # 用户信息


class Mailbox(models.Model):
    userinfo = models.ForeignKey('UserInfo', on_delete=models.CASCADE, verbose_name='用户')
    mailbox = models.CharField(max_length=32, verbose_name='邮箱')
    class Meta:
        verbose_name_plural = '用户邮箱'

    def __str__(self):
        return self.userinfo.account
    # 用户邮箱


class School(models.Model):
    school = models.CharField(max_length=32, verbose_name='学校')

    class Meta:
        verbose_name_plural = '学校信息'

    def __str__(self):
        return self.school
    # 学校信息


class MH_PersonalDetail(models.Model):
    cover = RichTextUploadingField(verbose_name="封面")
    name = models.CharField(max_length=32, verbose_name='姓名')
    gender = models.CharField(max_length=2, verbose_name='性别', choices=(('1', '男'), ('2', '女')))
    age = models.CharField(max_length=32, verbose_name='年龄')
    region = models.CharField(max_length=32, verbose_name='地区')
    school = models.ForeignKey('School', on_delete=models.CASCADE, verbose_name='学校')
    contact = models.CharField(max_length=32, verbose_name='联系方式')
    introduction = RichTextUploadingField(verbose_name='个人简介')
    user_collection = models.ManyToManyField(UserInfo, related_name='mh_personal_detail')

    class Meta:
        verbose_name_plural = '盲盒信息'

    def __str__(self):
        return "来自" + self.school.school + "的" + self.name
    # 盲盒信息


class Comment(models.Model):
    userinfo = models.ForeignKey('UserInfo', on_delete=models.CASCADE, verbose_name='昵称')
    mh = models.ForeignKey('MH_PersonalDetail', on_delete=models.CASCADE, verbose_name='盲盒')
    comment = RichTextUploadingField(verbose_name='评论', config_name='comment')

    class Meta:
        verbose_name_plural = '评论'

    def __str__(self):
        return "来自" + self.userinfo.account + "对来自" + self.mh.school.school + "的" + self.mh.name + "的评论"
    # 评论


class Comment_comment(models.Model):
    userinfo = models.ForeignKey('UserInfo', on_delete=models.CASCADE, verbose_name='昵称')
    post = models.ForeignKey('Comment', on_delete=models.CASCADE, verbose_name='盲盒评论')
    comment = RichTextUploadingField(verbose_name='评论的评论', config_name='comment')

    class Meta:
        verbose_name_plural = '评论的评论'

    def __str__(self):
        return "来自" + self.userinfo.account + "对来自" + self.post.userinfo.account + "所评论的内容的评论"
    # 评论的评论

templates/extract.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>抽取盲盒</title>
</head>
<style>
    body {text-align: center}
</style>
<body>
    <h1 style="color: green">抽取盲盒</h1>
    <form action="/mh/mh_detail/" method="post">
        {% csrf_token %}
        <input type="hidden" name="way" value="extract">
        <p style="color: green">性别：</p>
        <input type="radio" name="select_gender" value="0" checked="true"/>所有
        <input type="radio" name="select_gender" value="1"/>男
        <input type="radio" name="select_gender" value="2"/>女<br />
        <p style="color: green">学校：</p>
        <select name="select_school">
                <option value="0">所有</option>
                {% for a in school %}
                    <option value="{{a.school}}">{{ a.school }}</option>
                {% endfor %}
        </select><br/><br/>
        <input type = "submit" value = "抽取">
    </form>
    <!--抽取盲盒-->
    <table>
    <h2 style="color: green">盲盒详情</h2>
    <img src="{{ MEDIA_URL }}{{ personal_detail.cover }}">
        <p style="color: green">姓名：</p>
        <p style="color: black">{{ personal_detail.name }}</p>
        <p style="color: green">性别：</p>
        <p style="color: black">{{ personal_detail.get_gender_display }}</p>
        <p style="color: green">年龄：</p>
        <p style="color: black">{{ personal_detail.age }}</p>
        <p style="color: green">学校：</p>
        <p style="color: black">{{ personal_detail.school }}</p>
        <p style="color: green">地区：</p>
        <p style="color: black">{{ personal_detail.region }}</p>
        <p style="color: green">联系方式</p>
        <p style="color: black">{{ personal_detail.contact }}</p>
        <p style="color: green">个人简介</p>
        <p style="color: black">{{ personal_detail.introduction }}</p>
        <img src="{{ MEDIA_URL }}{{ personal_detail.photo }}">
        <p style="color: green">评论内容</p>
        {% for a in personal_detail1 %}
            <p style="color: green">{{ a.userinfo.name }}</p>
            <p style="color: black">{{ a.comment }}</p>
            {% for b in comment_comment %}
                {% if b.post == a %}
                    <p style="color: green;margin-left: 50px">{{ b.userinfo.name }}</p>
                    <p style="color: black;margin-left: 50px">{{ b.comment }}</p>
                {% endif %}
            {% endfor %}
            <form action = "/detail/" method="post" style="margin-left: 100px">
                {% csrf_token %}
                <p style="color: green">回复</p>
                <input type = "hidden" name= "id" value="{{ personal_detail.id }}" readonly>
                <input type = "hidden" name= "id1" value="{{ a.id }}" readonly>
                <input type = "hidden" name= "way" value="comment_comment" readonly>
                <textarea name = "comment" style="width: 300px;
                height: 100px;overflow-x: hidden" ></textarea><br />
                <input type = "submit" value = "确定发布">
            </form>
        {% endfor %}
        <form action = "/detail/" method="post">
            {% csrf_token %}
            <p style="color: green">评论</p>
            <input type = "hidden" name= "id" value="{{ personal_detail.id }}" readonly>
            <input type = "hidden" name= "way" value="comment" readonly>
            <textarea name = "comment" style="width: 300px;
            height: 100px;overflow-x: hidden" ></textarea><br />
            <input type = "submit" value = "确认">
        </form>
    </table>
    <br/><button onclick = "window.location.href = 'http://127.0.0.1:8000/'">退出</button>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%  if request.session.user_name %}
        <title>{{ request.session.user_name }}的主页</title>
    {% else %}
        <title>登录</title>
    {% endif %}
</head>
<style>
    body {text-align: center}
</style>
<body>
    {%  if request.session.account %}
        <h1 style="color: green">{{ request.session.user_name }}的主页</h1>
        <button onclick = "window.location.href = 'http://127.0.0.1:8000/user_detail/'">用户信息</button><br/><br/>
        <button onclick = "window.location.href = 'http://127.0.0.1:8000/user_collection/'">收藏夹</button><br/><br/>
        <button onclick = "window.location.href = 'http://127.0.0.1:8000/mh/'">盲盒一览</button><br/><br/>
        <button onclick = "window.location.href = 'http://127.0.0.1:8000/mh/mh_forum/'">盲盒论坛</button><br/><br/>
        <button onclick = "window.location.href = 'http://127.0.0.1:8000/place/'">放置盲盒</button><br/><br/>
        <button onclick = "window.location.href = 'http://127.0.0.1:8000/extract/'">抽取盲盒</button><br/><br/>
        <button onclick = "window.location.href = 'http://127.0.0.1:8000/flush/'">登出</button><br/><br/>
    {%  else %}
        <h1 style="color: green">登录</h1>
        <form action="" method="post">
        {% csrf_token %}
            账号：<input type = "text" name = "login_account" placeholder="请输入用户名" id="login_account" /><br/>
            密码：<input type = "password" name = "login_password" placeholder="请输入密码" id="login_password" /><br/><br/>
            <input type = "submit" value = "登录" disabled="disabled" id="login" ><br/><br/>
        </form>
        <button onclick = "window.location.href = 'http://127.0.0.1:8000/register/'">注册</button><br/><br/>
        <button onclick = "window.location.href = 'http://127.0.0.1:8000/retrieve_password/'">找回密码</button><br/><br/>
        <button onclick = "window.location.href = 'http://127.0.0.1:8000/extract/'">抽取盲盒</button><br/><br/>
    {% endif %}
</body>
<script>
    const login = document.getElementById('login');
    function judge(){
        const login_account = document.getElementById('login_account').value;
        const login_password = document.getElementById('login_password').value;
        if(login_account.length > 0 && login_password.length > 0)
        {
            login.removeAttribute('disabled');
        }
        else
        {
            login.setAttribute('disabled', 'disabled');
        }
    }
    setInterval('judge()', 500);
    {% for msg in messages %}
        alert('{{ msg.message }}');
    {% endfor %}
</script>
</html>

templates/mailbox.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>邮箱验证码</title>
</head>
<body>

</body>
</html>
<script>
    {% for msg in messages %}
        alert('{{ msg.message }}');
        window.history.back(-1);
    {% endfor %}
</script>

templates/mh.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>盲盒一览</title>
</head>
<style>
    body {text-align: center}
    table {margin: auto; border-collapse: collapse}
    td {text-align: center; border-style: double}
</style>
<body>
    <h1 style="color: green">盲盒一览</h1>
        <table>
            <thead>
                <tr>
                    <td>姓名</td>
                    <td>性别</td>
                    <td>年龄</td>
                    <td>地区</td>
                    <td>联系方式</td>
                    <td>个人简介&#09</td>
                    <td>操作&#09</td>
                </tr>
            </thead>
            <tbody>
                {% for item in user_list %}
                <tr>
                    <td>{{ item.boxdetail.name }}&#09</td>
                    <td>{{ item.boxdetail.get_gender_display }}&#09</td>
                    <td>{{ item.boxdetail.age }}&#09</td>
                    <td>{{ item.boxdetail.region }}&#09</td>
                    <td>{{ item.boxdetail.contact }}&#09</td>
                    <td>{{ item.boxdetail.introduction }}&#09</td>
                    <td>
                        <form action="/user_collection/" method="post">
                            {% csrf_token %}
                            <input type="submit" value="收藏">&#09
                            <input type="hidden" name="id" value="{{ item.boxdetail.id }}"><br/><br/>
                        </form>
                        <form action="/delete/" method="post">
                            {% csrf_token %}
                            <input type="submit" value="删除">&#09
                            <input type="hidden" name="way" value="record_delete">
                            <input type="hidden" name="id" value="{{ item.boxdetail.id }}">
                        </form></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    <br/><button onclick = "window.location.href = 'http://127.0.0.1:8000/'">退出</button>
</body>
</html>

templates/mh_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>盲盒详细页</title>
</head>
<style>
    body {text-align: center}
</style>
<body>
    <h1 style="color: green">盲盒详细页</h1>
        <img src="{{ MEDIA_URL }}{{ mh_personaldetail.cover }}">
        <p style="color: green">姓名：</p>
        <p style="color: black">{{ mh_personaldetail.name }}</p>
        <p style="color: green">性别：</p>
        <p style="color: black">{{ mh_personaldetail.get_gender_display }}</p>
        <p style="color: green">年龄：</p>
        <p style="color: black">{{ mh_personaldetail.age }}</p>
        <p style="color: green">学校：</p>
        <p style="color: black">{{ mh_personaldetail.school }}</p>
        <p style="color: green">地区：</p>
        <p style="color: black">{{ mh_personaldetail.region }}</p>
        <p style="color: green">联系方式</p>
        <p style="color: black">{{ mh_personaldetail.contact }}</p>
        <p style="color: green">个人简介</p>
        <p style="color: black">{{ mh_personaldetail.introduction }}</p>
        <img src="{{ MEDIA_URL }}{{ personal_detail.photo }}">
        <p style="color: green">评论内容</p>
        {% for comment in mh_personaldetail.comment %}
            <p style="color: green">{{ a.userinfo.name }}</p>
            <p style="color: black">{{ a.comment }}</p>
            {% for b in comment_comment %}
                {% if b.post == a %}
                    <p style="color: green;margin-left: 50px">{{ b.userinfo.name }}</p>
                    <p style="color: black;margin-left: 50px">{{ b.comment }}</p>
                {% endif %}
            {% endfor %}
            <form action = "/detail/" method="post" style="margin-left: 100px">
                {% csrf_token %}
                <p style="color: green">回复</p>
                <input type = "hidden" name= "id" value="{{ personal_detail.id }}" readonly>
                <input type = "hidden" name= "id1" value="{{ a.id }}" readonly>
                <input type = "hidden" name= "way" value="comment_comment" readonly>
                <textarea name = "comment" style="width: 300px;
                height: 100px;overflow-x: hidden" ></textarea><br />
                <input type = "submit" value = "确认">
            </form>
        {% endfor %}
        <form action = "/detail/" method="post">
            {% csrf_token %}
            <p style="color: green">评论</p>
            <input type = "hidden" name= "id" value="{{ personal_detail.id }}" readonly>
            <input type = "hidden" name= "way" value="comment" readonly>
            <textarea name = "comment" style="width: 300px;
            height: 100px;overflow-x: hidden" ></textarea><br />
            <input type = "submit" value = "确认">
        </form>
        <button onclick = "window.location.href = 'http://127.0.0.1:8000/'">退出</button>
</body>
</html>

templates/mh_forum.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>盲盒论坛</title>
</head>
<style>
    body {text-align: center}
</style>
<body>
    <h1 style="color: green">盲盒论坛</h1>
    <p style="color: green">性别：</p>
    <input type="radio" name="select_gender" value="0" checked/>所有
    <input type="radio" name="select_gender" value="1"/>男
    <input type="radio" name="select_gender" value="2"/>女<br />
    {% for mh in page %}
        <p style="color: green">姓名：{{ mh.name }}</p>
        <p style="color: green">年龄：{{ mh.age }}</p>
        <p style="color: green">地区：{{ mh.region }}</p>
        <form action="/detail/" method="post">
            {% csrf_token %}
            <input type = "hidden" name = "id" value="{{ mh.id }}" readonly/>
            <input type = "hidden" name = "way" value= "detail" readonly/>
            <input type = "submit" value = "详细内容">
        </form>
    {% endfor %}
    <form action="/mh_forum/" method="get">
    {% csrf_token %}
        <p style="color: green">页数：</p>
    {% for page in page_range %}
        <input type="radio" name="current_page" value="{{ page }}"/>{{ page }}
    {% endfor %}
    <br /><br />
        <input type = "submit" value = "翻页">
    </form>
    <br/><button onclick = "window.location.href = 'http://127.0.0.1:8000/'">退出</button>
<script>
    setInterval('judge()', 500);
</script>
</body>
</html>

templates/place.html
<!DOCTYPE html>
<html lang = "en">
<head>
    <meta charset="UTF-8">
    <title>放置盲盒</title>
</head>
<style>
    body {text-align: center}
</style>
<body>
    <h1 style="color: green">放置盲盒</h1>
    <form action = "" method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        <p style="color: green">封面<br /></p>
            {{ mh_personaldetail_form.media }}
            {{ mh_personaldetail_form.cover }}<br />
        姓名：{{ mh_personaldetail_form.name }}<br />
        性别：{{ mh_personaldetail_form.gender }}<br />
        年龄：{{ mh_personaldetail_form.age }}<br />
        地区：{{ mh_personaldetail_form.region }}<br />
        学校：{{ mh_personaldetail_form.school }}<br />
        联系方式：{{ mh_personaldetail_form.contact }}<br />
        个人简介：{{ mh_personaldetail_form.introduction }}<br />
        <input type = "submit" value="提交">
    </form>
    <button onclick = "window.location.href = 'http://127.0.0.1:8000/'">退出</button>
    {% if messages %}
    <script>
          {% for msg in messages %}
                alert('{{ msg.message }}');
                window.history.back(-1);
            {% endfor %}
    </script>
    {% endif %}
</body>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<style>
    body {text-align: center}
</style>
<body>
    <h1 style="color: green">注册</h1>
    <form method="post">
        {% csrf_token %}
        账号：<input type="text" name="register_account" placeholder="请输入用户名" id="register_account"/><br/>
        邮箱：<input type="text" name="register_mailbox" placeholder="请输入邮箱" id="register_mailbox"/><br/>
        密码：<input type="password" name="register_password" placeholder="请输入密码" id="register_password"/><br/>
        确认密码：<input type="password" name="register_re_password" placeholder="请再一次输入密码" id="register_re_password"/><br/>
        验证码：<input type="password" name="register_verification_code_input" placeholder="请输入验证码" id="verification_code_input"/>
        <br/><br/><input type="submit" value="注册" disabled="disabled" id="register"><br/><br/>
    </form>
    <form action="/mailbox/" method="post">
        {% csrf_token %}
        <input type="hidden" name="mailbox" id="mailbox"/><br/>
        <input type="submit" value="发送验证码" disabled="disabled" id="verification_code"><br/><br/>
    </form>
    <button onclick = "window.location.href = 'http://127.0.0.1:8000/'">返回</button><br />
    <script>
        const register = document.getElementById('register');
        const verification_code = document.getElementById('verification_code');
        function judge()
        {
            var register_account = document.getElementById('register_account').value;
            var register_password = document.getElementById('register_password').value;
            var register_re_password = document.getElementById('register_re_password').value;
            var register_mailbox = document.getElementById('register_mailbox').value;
            var verification_code_input = document.getElementById('verification_code_input').value;
            if(register_account.length > 0 && register_password.length > 0 && register_re_password.length > 0 &&
                register_mailbox.length > 0 && verification_code_input.length > 0)
            {
                register.removeAttribute('disabled');
            }
            else
            {
                register.setAttribute('disabled', 'disabled');
            }
            if(register_mailbox.length > 0)
            {
                const mailbox = document.getElementById('mailbox');
                mailbox.setAttribute('value', register_mailbox);
                verification_code.removeAttribute('disabled');
            }
            else
            {
                verification_code.setAttribute('disabled', 'disabled');
            }
        }
        setInterval('judge()', 500);
        {% for msg in messages %}
            alert('{{ msg.message }}');
            window.history.back(-1);
        {% endfor %}
    </script>
</body>
</html>

templates/retrieve_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>找回密码</title>
</head>
<style>
    body {text-align: center}
</style>
<body>
    <h1 style="color: green">忘记密码</h1>
    <form method="post">
        {% csrf_token %}
        账号：<input type="text" name="account_input" placeholder="请输入用户名" id="account_input"/><br/>
        邮箱：<input type="text" name="mailbox_input" placeholder="请输入邮箱" id="mailbox_input"/><br/>
        新密码：<input type="password" name="password_input" placeholder="请输入密码" id="password_input"/><br/>
        确认密码：<input type="password" name="re_password_input" placeholder="请再一次输入密码" id="re_password_input"/><br/>
        验证码：<input type="password" name="verification_code_input" placeholder="请输入验证码" id="verification_code_input"/>
        <br/><br/><input type="submit" value="确定" disabled="disabled" id="sure"><br/><br/>
    </form>
    <form action="/mailbox/" method="post">
        {% csrf_token %}
        <input type="hidden" name="mailbox" id="mailbox"/><br/>
        <input type="submit" value="发送验证码" disabled="disabled" id="verification_code"><br/><br/>
    </form>
    <button onclick = "window.location.href = 'http://127.0.0.1:8000/'">退出</button><br/><br/>
</body>
<script>
    const register = document.getElementById('sure');
    const verification_code = document.getElementById('verification_code');
    function judge()
    {
        var account_input = document.getElementById('account_input').value;
        var mailbox_input = document.getElementById('mailbox_input').value;
        var password_input = document.getElementById('password_input').value;
        var re_password_input = document.getElementById('re_password_input').value;
        var verification_code_input = document.getElementById('verification_code_input').value;
        if(account_input.length > 0 && mailbox_input.length > 0 && password_input.length > 0 &&
            re_password_input.length > 0 && verification_code_input.length > 0)
        {
            register.removeAttribute('disabled');
        }
        else
        {
            register.setAttribute('disabled', 'disabled');
        }
        if(mailbox_input.length > 0)
        {
            const mailbox = document.getElementById('mailbox');
            mailbox.setAttribute('value', mailbox_input);
            verification_code.removeAttribute('disabled');
        }
        else
        {
            verification_code.setAttribute('disabled', 'disabled');
        }
    }
    setInterval('judge()', 500);
    {% for msg in messages %}
        alert('{{ msg.message }}');
        window.history.back(-1);
    {% endfor %}
</script>
</html>

templates/user_collection.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>收藏夹</title>
</head>
<style>
    body {text-align: center}
    table {margin: auto; border-collapse: collapse}
    td {text-align: center; border-style: double}
</style>
<body>
    <h1 style="color: green">收藏内容</h1>
        <table border="1">
            <thead>
                <tr>
                    <td>姓名&#09</td>
                    <td>性别&#09</td>
                    <td>年龄&#09</td>
                    <td>地区&#09</td>
                    <td>联系方式&#09</td>
                    <td>个人简介&#09</td>
                    <td>操作&#09</td>
                </tr>
            </thead>
            <tbody>
                {% for item in user_collection %}
                <tr>
                    <td>{{ item.box.name }}&#09</td>
                    <td>{{ item.box.get_gender_display }}&#09</td>
                    <td>{{ item.box.age }}&#09</td>
                    <td>{{ item.box.region }}&#09</td>
                    <td>{{ item.box.contact }}&#09</td>
                    <td>{{ item.box.introduction }}&#09</td>
                    <form action="/delete/" method="post">
                        {% csrf_token %}
                        <td><input type="submit" value="删除">&#09</td>
                        <input type="hidden" name="way" value="user_collection_delete">
                        <input type="hidden" name="id" value="{{ item.box.id }}">
                    </form>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    <br/><button onclick = "window.location.href = 'http://127.0.0.1:8000/'">退出</button>
</body>
</html>

templates/user_detail.html
<!DOCTYPE html>
<html lang = "en">
<head>
    <meta charset="UTF-8">
    <title>用户信息页</title>
</head>
<style>
    body {text-align: center}
</style>
<body>
    <h1 style="color: green">用户信息页</h1>


    <form action = "/user_detail/" method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        <p style="color: green">头像</p><br />
        <img src="{{ MEDIA_URL }}{{ user.portrait }}">
        <input type = "hidden" name= "way" value="portrait_change" readonly>
        <p>
            <input type="file" name="portrait">
        </p>
            <input type="submit" value="上传">
        </p>
    </form>
    <!--头像-->



    <p style="color: green">账号：{{ user.account }}</p>

    {% if way == 'name_change' %}
        <form action = "/user_detail/" method = "post">
            {% csrf_token %}
            <p style="color: green">昵称：
                <input type = "text" name = "name"/>
                <input type = "submit" value = "确认修改">
            </p>
            <input type = "hidden" name= "way" value="name_change_finish" readonly>
        </form>
    {% else %}
        <form action = "/user_detail/" method = "post">
            {% csrf_token %}
            <p style="color: green">用户名：{{ user.user_name }}
                <input type = "hidden" name= "way" value="name_change" readonly>
                <input type = "submit" value = "修改">
            </p>
        </form>
    {% endif %}



    {% if way == 'region_change' %}
        <form action = "/user_detail/" method = "post">
            {% csrf_token %}
            <p style="color: green">地区：
               <input type = "text" name = "region"/>
                <input type = "submit" value = "确认修改">
                <input type = "hidden" name= "way" value="region_change_finish" readonly>
            </p>
        </form>
    {% else %}
        <form action = "/user_detail/" method = "post">
            {% csrf_token %}
            <p style="color: green">地区：{{ user.region }}
            <input type = "hidden" name= "way" value="region_change" readonly>
            <input type = "submit" value = "修改">
            </p>
        </form>
    {% endif %}



    <br/><button onclick = "window.location.href = 'http://127.0.0.1:8000/'">退出</button>
    <script>
{% if messages %}
          {% for msg in messages %}
                alert('{{ msg.message }}');
          {% endfor %}
{% endif %}
    </script>
</body>